In [1]:
# Ensure working directory to project code folder
import os

# Edit this path to point at your local `code/` folder (the directory containing `GridMaze/`).
os.chdir("/ceph/behrens/peter_doohan/goalNav_mFC_refactor/code")
print("Current Working Directory: ", os.getcwd())

Current Working Directory:  /ceph/behrens/peter_doohan/goalNav_mFC_refactor/code

# How to load behavioural data from for your own analyses

GridMaze data is organised in a stardarised format, see (notebook_that_will_soon_exist.ipynb) for details on how the data is organised on disk & how we access it for the analyses in this repo.

In short, we organise all data at the subject/session level and access the data we want using a ```get_maze_sessions``` function that lives in ```GridMaze.analysis.core.get_sessions```. However, if you'd like to load all the behavioural data in a single table/dataframe for your own analysis, use the code below :)

You can load behavioural data at either node-by-node resolution or frame-by-frame resolution. 

Note:
- Run the code below in a conda environment with the packages specified in ```GridMaze_mFC_refactor/code/requirements.txt```
- Recommended have >32GB RAM for loading frame-by-frame data.

### Load node-by-node data

In [7]:
import pandas as pd
from GridMaze.analysis.core import get_sessions as gs

# load data
data_structures = ["trajectory_decisions_df"]  # load trajectory_decisions_df for node-by-node behaavioural data

sessions = gs.get_maze_sessions(
    subject_IDs="all",
    maze_names="all",
    days_on_maze="all",
    with_data=data_structures,
    must_have_data=True,
)

# combine data across sessions into a single dataframe
behaviour_df = pd.concat([session.trajectory_decisions_df for session in sessions])

behaviour_df.head()

,subject_ID,maze_name,day_on_maze,time,trial,trial_unique_ID,trial_phase,goal,maze_position,action,geodesic_distance_to_goal,steps_to_goal
0,m2,maze_2,11,-4.366901,NaN,NaN,NaN,NaN,D6,S,NaN,NaN
1,m2,maze_2,11,-2.058349,NaN,NaN,NaN,NaN,D5-D6,S,NaN,NaN
2,m2,maze_2,11,0.250203,NaN,NaN,NaN,NaN,D5,W,NaN,NaN
3,m2,maze_2,11,1.034173,NaN,NaN,NaN,NaN,C5-D5,W,NaN,NaN
4,m2,maze_2,11,1.818142,NaN,NaN,NaN,NaN,C5,W,NaN,NaN

In [ ]:
# save where you want
save_path = "your/path/here"
behaviour_df.to_csv(save_path, index=False)

### Load frame-by-frame data

Note we can load this with or without route (Xiao™) info

In [ ]:
import pandas as pd
from GridMaze.analysis.core import get_sessions as gs

# load data with specified inputs
with_routes = True
data_structures = ["navigation_df", "navigation_routes_df"] if with_routes else ["navigation_df"]

sessions = gs.get_maze_sessions(  # loading alot of data into memory, will take a few mins (recommend 128GB RAM)
    subject_IDs="all",
    maze_names="all",
    days_on_maze="all",
    with_data=data_structures,
    must_have_data=True,
)

In [8]:
# combine data across sessions into a single dataframe
if with_routes:
    behaviour_dfs = []
    for s in sessions:
        behaviour_dfs.append(pd.concat([s.navigation_df, s.navigation_routes_df.reset_index(drop=True)], axis=1))
else:
    behaviour_dfs = [s.navigation_df for s in sessions]

behaviour_df = pd.concat(behaviour_dfs, axis=0, ignore_index=True)

behaviour_df.head()

       time subject_ID maze_name day_on_maze trial_unique_ID trial  \

0 -4.366901         m2    maze_2          11             NaN   NaN
1 -4.350233         m2    maze_2          11             NaN   NaN
2 -4.333566         m2    maze_2          11             NaN   NaN
3 -4.316898         m2    maze_2          11             NaN   NaN
4 -4.300231         m2    maze_2          11             NaN   NaN

  trial_phase goal head_direction centroid_position  ... route            \
                            value                 x  ...   r-2  r-3  r-4
0         NaN  NaN     263.980808          0.692806  ...   NaN  NaN  NaN
1         NaN  NaN     266.824893          0.694574  ...   NaN  NaN  NaN
2         NaN  NaN     264.838046          0.692649  ...   NaN  NaN  NaN
3         NaN  NaN     261.311944          0.692923  ...   NaN  NaN  NaN
4         NaN  NaN     259.310344          0.692445  ...   NaN  NaN  NaN

  route_change n_routes route_order           route_progress              \
                            to_goal from_goal           time path_length
0          NaN      NaN         NaN       NaN            NaN         NaN
1          NaN      NaN         NaN       NaN            NaN         NaN
2          NaN      NaN         NaN       NaN            NaN         NaN
3          NaN      NaN         NaN       NaN            NaN         NaN
4          NaN      NaN         NaN       NaN            NaN         NaN

  optimal_route

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN

[5 rows x 55 columns]

In [ ]:
# save where you want
save_path = "your/path/here"
behaviour_df.to_csv(save_path, index=False)